vim.keymap.set("n", "<leader>db", vim.cmd.DapToggleBreakpoint)
vim.keymap.set("n", "<leader>dd", function ()
    local widgets = require("dap.ui.widgets")
    local sidebar = widgets.sidebar(widgets.scopes)
    sidebar.open()
end)
vim.keymap.set("n", "<leader>dn", vim.cmd.DapStepOver)
vim.keymap.set("n", "<leader>dt", function ()
    require'dap'.disconnect({ terminateDebuggee = true })
end)
