local plugins = {
	require("plugins.colorschemes"),
	require("plugins.which-key"),
	require("plugins.telescope"),
	require("plugins.plenary"),
	require("plugins.tokyonight"),
	require("plugins.treesitter"),
    require("plugins.toggleterm"),
    require("plugins.rose-pine"),
    require("plugins.harpoon"),
    require("plugins.undotree"),
    require("plugins.lsp-plugins"),
    require("plugins.mini-nvim"),
    require("plugins.nwm"),
    require("plugins.debug"),
    require("plugins.rust-tools"),
    require("plugins.autoclose"),
    require("plugins.flash"),
    require("plugins.nvim-notify"),
    require("plugins.silicon"),
    require("plugins.prettier"),
    require("plugins.ts-autotag"),
    require("plugins.go"),
    require("plugins.todo-comments"),
    require("plugins.noice"),
}

return plugins
